### ISSUE TITLE
Trigger matching

### ISSUE THREAD

**Issue by lucastorterotot** [GaelTouquet/cmgtools-lite#9]
While exploring event 2539312 in et channel it turned out [this condition](https://github.com/GaelTouquet/cmgtools-lite/blob/htt_9_4_11_cand1_v1/H2TauTau/python/heppy/analyzers/TrigMatcher.py#L106) never occurs with
```
info.name == 'HLT_Ele24_eta2p1_WPTight_Gsf_LooseChargedIsoPFTau30_eta2p1_CrossL1_v9'
```
while `info.leg1_names` is equal to
```
[['hltEle24erWPTightGsfTrackIsoFilterForTau', 'hltOverlapFilterIsoEle24WPTightGsfLooseIsoPFTau30'], ['hltOverlapFilterIsoEle24WPTightGsfLooseIsoPFTau30']]
```
and `diL.leg1().triggernames` to
```
set(['hltOverlapFilterIsoEle24WPTightGsfLooseIsoPFTau30'])
```
and even
```
10000000000000000 > diL.leg1().triggernames
```
returns `False`. I think we do not compare comparable things here.

Is there a problem or am I mistaken? What to do?

**Comment by GaelTouquet** [comment]
Thanks for pointing out this issue!
First, I don't really understand how info.leg1_names end up having this value, since it is set [here](https://github.com/GaelTouquet/cmgtools-lite/blob/htt_9_4_11_cand1_v1/H2TauTau/python/proto/samples/fall17/triggers_tauEle.py#L35) and only is the first element of the list you get.
Second there is an obvious typo here where I think the line : 
```
len(info.leg1_names) > diL.leg1().triggernames:
```
Should be replaced as : 
```
len(info.leg1_names) > len(diL.leg1().triggernames):
```
Even so, I'm not sure that this line accomplishes its goal. It seems what it should be is : 
```
not all([x in diL.leg1().triggernames for x in info.leg1_names]):
```
If you could test whether this fix makes the sync better/worse, this would be very appreciated!

**Comment by lucastorterotot** [comment]
I'll try to find out. I'll make a PR if I find a way to get a better sync.

**Comment by lucastorterotot** [comment]
I just started a SyncNtuple production to test [this commit](https://github.com/lucastorterotot/cmgtools-lite/commit/6023eb7923281ba4735fe7874b52a82722a757d1).

**Comment by lucastorterotot** [comment]
About  `info.leg1_names` definition, for the `info` called [here](https://github.com/GaelTouquet/cmgtools-lite/blob/htt_9_4_11_cand1_v1/H2TauTau/python/heppy/analyzers/TrigMatcher.py#L91) is defined [in the trigger analyzer](https://github.com/GaelTouquet/cmgtools-lite/blob/htt_9_4_11_cand1_v1/H2TauTau/python/proto/analyzers/TriggerAnalyzer.py#L188). To actually get [what is set in the configuration file](https://github.com/GaelTouquet/cmgtools-lite/blob/htt_9_4_11_cand1_v1/H2TauTau/python/proto/samples/fall17/triggers_tauEle.py#L35), one has to use `info.match_infos` as you can see [here](https://github.com/lucastorterotot/cmgtools-lite/commit/6023eb7923281ba4735fe7874b52a82722a757d1#diff-d4649e8b8d7823887efe828dbb52277fR107). The definition of `info.match_infos` is also [in the trigger analyzer](https://github.com/GaelTouquet/cmgtools-lite/blob/htt_9_4_11_cand1_v1/H2TauTau/python/proto/analyzers/TriggerAnalyzer.py#L190), but a few lines below the definition of  `info.leg1_names`.

**Comment by lucastorterotot** [comment]
Ok so [this previous change](https://github.com/lucastorterotot/cmgtools-lite/commit/6023eb7923281ba4735fe7874b52a82722a757d1#diff-d4649e8b8d7823887efe828dbb52277f) made some small improvements
 It seems like another problem is [this pT cut](https://github.com/GaelTouquet/cmgtools-lite/blob/htt_9_4_11_cand1_v1/H2TauTau/python/heppy/analyzers/TrigMatcher.py#L157) as you told me earlier. I do not remember if we asked Arthur what this cut is really about and if it changes over channels.
The situation is the following :
* et channel
trg_singleelectron_27 synced
trg_singleelectron_32 synced
trg_singleelectron_35 NOT synced
trg_crossele_ele24tau30 NOT synced
* mt channel
trg_singlemuon_24 synced
trg_singlemuon_27 synced
trg_crossmuon_mu20tau27 NOT synced

Each time we do not sync, we have too many event with trg variable at 0 instead of 1.
I am now trying without this pT cut at ~ 32 GeV.

**Comment by lucastorterotot** [comment]
A solution has been proposed in [this PR](https://github.com/GaelTouquet/cmgtools-lite/pull/7). the modification on the pT cut has been made at [this commit](https://github.com/GaelTouquet/cmgtools-lite/pull/7/commits/1836d2355474438d5502c13f16dd5256d11645e1).
